### ISSUE TITLE
flistd: add cache directory indirection to avoid large directory size

### ISSUE THREAD

**Issue by maxux** [threefoldtech/0-fs#41]
@delandtj noticed some large usage of `flist cache` directory, like `7M` directory size, which is not optimal at all for storage.
An easy workaround to fix that is using indirection like `cache/fa/db/abcd00123...` (for hash `fadbabcd00123...`)
An alternative could also be `fa/db/fadbabcd00123` in order to keep filename as full hash.

**Comment by zaibon** [comment]
moved this issue from https://github.com/threefoldtech/zos to this repo since the organization of the files of the cache is management by 0-fs itself, not 0-OS
