### ISSUE TITLE
flist changes

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/0-fs#7]
- No more CRC and header on the backend (you can directly use the full payload, no [:16] or so to do
- Sqlite, file is flistdb.sqlite3 inside the tar, table is entries with key, value as fields
- Use blake2 for all hash, no sha/md5. Use keylength of 16 for blake2 hash (same length as md5)
- Hash are in binary on the blocks fields, no more string (don't try to print them without converting to hex)

**Comment by zaibon** [comment]
fixed in fe2c04a520941a3cc06caf6a11ab0d9140befe35
